name: Create theme release

on:
  workflow_dispatch:
    inputs:
      version_number:
        description: The version number to release
        default: "0.1.0"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    # TODO: Add release ZIP file creation
    - name: Create zip files
      run: |
        ls
        for theme in */ ; do
            if [ -d "$theme" ]; then
                echo "${theme%/}"
                FILENAME="${theme%/}_${{ github.event.inputs.version_number }}.zip"
                echo "$FILENAME $theme"
                zip -r $FILENAME $theme
            fi
        done
        ls

    # TODO: Add step to release ZIP files to releases page

